apiVersion: apps/v1
kind: Deployment
metadata: 
  name: address-book-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
       app: address-book
  template:
    metadata:
      labels: 
        app: address-book
    spec:
      containers:
      - name: app-container
        image: hellolove123/cab-booking-app:4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: address-book-service
spec:
  type: NodePort
  selector:
    app: address-book
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
